# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /home/akos # The home of Ãkos
email:
description: > # this means to ignore newlines until "baseurl:"
    This is my home on the internet where I try to post interesting stuff.
    Unfortunately I am lazy to do so. But, don't panic!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://akoskovacs.github.io" # the base hostname & protocol for your site
twitter_username: sokacsavok
github_username:  akoskovacs
excerpt_separator: <!--more-->
# Build settings
markdown:  kramdown
pigments: true

kramdown:
  input: GFM
